// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjv25lnomdZqfLDv-mh3eBq3NAzJA5eLs',
    appId: '1:4880858039:web:b5e16de6e7e139e6ff4632',
    messagingSenderId: '4880858039',
    projectId: 'classmate-d2d4d',
    authDomain: 'classmate-d2d4d.firebaseapp.com',
    storageBucket: 'classmate-d2d4d.appspot.com',
    measurementId: 'G-N02Y2ZD747',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuWjUfQ7GaaY-Ah6S4oyDjWDC2TWYdtbk',
    appId: '1:4880858039:android:a792ad7b7e0df01fff4632',
    messagingSenderId: '4880858039',
    projectId: 'classmate-d2d4d',
    storageBucket: 'classmate-d2d4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADc6SaFWuCKRrctDghoyAfTSaMk-fa7uw',
    appId: '1:4880858039:ios:504526405fafc51eff4632',
    messagingSenderId: '4880858039',
    projectId: 'classmate-d2d4d',
    storageBucket: 'classmate-d2d4d.appspot.com',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADc6SaFWuCKRrctDghoyAfTSaMk-fa7uw',
    appId: '1:4880858039:ios:32ff86fcf7335176ff4632',
    messagingSenderId: '4880858039',
    projectId: 'classmate-d2d4d',
    storageBucket: 'classmate-d2d4d.appspot.com',
    iosBundleId: 'com.example.classmate.RunnerTests',
  );
}
