// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRii9Gpkxz9mRR5gYbRAz-YBzfsXFSkc',
    appId: '1:489209908585:web:facc42b451c4250d4e81f8',
    messagingSenderId: '489209908585',
    projectId: 'classmates-be24a',
    authDomain: 'classmates-be24a.firebaseapp.com',
    storageBucket: 'classmates-be24a.appspot.com',
    measurementId: 'G-SSBYBL4FTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsUtWEcPjgxr698ol4--xkfXXUvPgkNTk',
    appId: '1:489209908585:android:4aa5c5a83f2ca5584e81f8',
    messagingSenderId: '489209908585',
    projectId: 'classmates-be24a',
    storageBucket: 'classmates-be24a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi4ixrnGcurhSJ-SycFhdPwrnx1nxgu3A',
    appId: '1:489209908585:ios:3f9647587dd413de4e81f8',
    messagingSenderId: '489209908585',
    projectId: 'classmates-be24a',
    storageBucket: 'classmates-be24a.appspot.com',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi4ixrnGcurhSJ-SycFhdPwrnx1nxgu3A',
    appId: '1:489209908585:ios:b07fca086e240e164e81f8',
    messagingSenderId: '489209908585',
    projectId: 'classmates-be24a',
    storageBucket: 'classmates-be24a.appspot.com',
    iosBundleId: 'com.example.classmate.RunnerTests',
  );
}
